### ISSUE TITLE
AoC day folders seem to be broken on GitHub side

### ISSUE THREAD

**Issue by ajhalili2006** [Ianyourgod/advent_of_code_2024#1]
Coming here from Hack Club High Seas's Wonderdome, it seems that you symlinked the folders outside the repo and I can't access them on the GitHub website. Could you please fix this?

**Comment by Ianyourgod** [comment]
So sorry. Yeah i'll try to fix them rq.

**Comment by Ianyourgod** [comment]
should work now. marking as resolved.
thank you for telling me :)
